# PostgreSQL. Versions 8.2 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On Mac OS X with macports:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.

development:
  adapter: postgresql
  encoding: unicode
  database: jampatch_development
  pool: 5
  username: <%= ENV['USER'] %>

test:
  adapter: postgresql
  encoding: unicode
  database: jampatch_test
  pool: 5
  username: <%= ENV['USER'] %>

production:
  adapter: postgresql
  encoding: unicode
  database: jampatch_production
  pool: 5
  username: <%= ENV['USER'] %>
